name: Deploy Serverless

on:
  workflow_dispatch:
  push:
    branches: [ master ]

defaults:
  run:
    working-directory: ./serverless

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install Serverless Framework
        run: npm i -g serverless

      - name: write .env file
        run: npx envdist testnet -e
        env:
          SLS_ORG: ${{ secrets.SLS_ORG }}
          SLS_APP: ${{ secrets.SLS_APP }}
          SLS_SERVICE: ${{ secrets.SLS_SERVICE }}
          SLS_TURRET_BASE_URL: ${{ secrets.SLS_TURRET_BASE_URL }}
          SLS_TURRET_SIGNER_ACCOUNT: ${{ secrets.SLS_TURRET_SIGNER_ACCOUNT }}
          SLS_AWS_PLAN: ${{ secrets.SLS_AWS_PLAN }}

      - name: Install dependencies
        run: yarn

      - name: Deploy Lambda function
        run: SLS_DEBUG=* SERVERLESS_ACCESS_KEY=${{ secrets.SERVERLESS_ACCESS_KEY }} sls deploy
